# Load saved MuMiN data

In [1]:
from mumin import MuminDataset

# Load saved dataset
twitter_bearer_token = 'AAAAAAAAAAAAAAAAAAAAAPhBdwEAAAAA8960MaR6BTtd9CDUHrfi2uaxYpU%3DrCAua60sKetPNDXBJjOg0plfXrQiw54We4OLTuI7gcMkHwuXZY'
dataset = MuminDataset(twitter_bearer_token=twitter_bearer_token)
dataset.compile()

/mnt/e/School Stuff/s2_uii/tesis/proposal/data/_build/pip_packages/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2022-06-24 16:52:51,717 [INFO] Loading dataset

MuminDataset(num_nodes=382,703, num_relations=465,648, size='small', compiled=True, bearer_token_available=True)

# Explore dataset

In [3]:
list(dataset.nodes.keys())

['claim', 'tweet', 'user', 'image', 'article', 'hashtag', 'reply']

In [2]:
tweet_df = dataset.nodes['tweet']
tweet_df

,tweet_id,text,created_at,lang,source,num_retweets,num_replies,num_quote_tweets
0,1238947475471454220,Antes de llegar a los pulmones dura 4 dÃ­as en ...,2020-03-14 21:57:51,es,Twitter for Android,8,3,0
1,1295062953000042496,Aeroporto de Dubai em chamas. ðŸ¤•ðŸ˜§ https://t.co/...,2020-08-16 18:20:43,pt,Twitter for Android,6,0,5
2,1294614020008312832,Fogo ðŸ”¥ no aeroporto de Dubai ðŸ˜±ðŸ˜± https://t.co/2...,2020-08-15 12:36:49,pt,Twitter for Android,24,11,7
3,1294701863489744896,Fogo no aeroporto de Dubai. https://t.co/yhQDe...,2020-08-15 18:25:53,pt,Twitter for Android,14,7,4
4,1295124644085805057,Incendio en el aeropuerto de Dubai https://t.c...,2020-08-16 22:25:52,es,Twitter for Android,33,5,3
...,...,...,...,...,...,...,...,...
4330,1228444529893789696,,NaT,NaN,,0,0,0
4331,1254824343646978053,,NaT,NaN,,0,0,0
4332,781079059690381312,,NaT,NaN,,0,0,0
4333,1105840789383454720,,NaT,NaN,,0,0,0
4334,1140646915455029254,,NaT,NaN,,0,0,0

In [3]:
tweet_df.dropna(inplace=True)
tweet_df.head()

,tweet_id,text,created_at,lang,source,num_retweets,num_replies,num_quote_tweets
0,1238947475471454220,Antes de llegar a los pulmones dura 4 dÃ­as en ...,2020-03-14 21:57:51,es,Twitter for Android,8,3,0
1,1295062953000042496,Aeroporto de Dubai em chamas. ðŸ¤•ðŸ˜§ https://t.co/...,2020-08-16 18:20:43,pt,Twitter for Android,6,0,5
2,1294614020008312832,Fogo ðŸ”¥ no aeroporto de Dubai ðŸ˜±ðŸ˜± https://t.co/2...,2020-08-15 12:36:49,pt,Twitter for Android,24,11,7
3,1294701863489744896,Fogo no aeroporto de Dubai. https://t.co/yhQDe...,2020-08-15 18:25:53,pt,Twitter for Android,14,7,4
4,1295124644085805057,Incendio en el aeropuerto de Dubai https://t.c...,2020-08-16 22:25:52,es,Twitter for Android,33,5,3

In [12]:
tweet_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4049 entries, 0 to 4048
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tweet_id          4049 non-null   uint64
 1   text              4049 non-null   object
 2   created_at        4049 non-null   datetime64[ns]
 3   lang              4049 non-null   category
 4   source            4049 non-null   object
 5   num_retweets      4049 non-null   uint64
 6   num_replies       4049 non-null   uint64
 7   num_quote_tweets  4049 non-null   uint64
dtypes: category(1), datetime64[ns](1), object(2), uint64(4)
memory usage: 258.4+ KB

In [6]:
list(dataset.rels.keys())

[('tweet', 'discusses', 'claim'),
 ('tweet', 'mentions', 'user'),
 ('tweet', 'has_image', 'image'),
 ('tweet', 'has_hashtag', 'hashtag'),
 ('tweet', 'has_article', 'article'),
 ('reply', 'reply_to', 'tweet'),
 ('reply', 'quote_of', 'tweet'),
 ('user', 'posted', 'tweet'),
 ('user', 'posted', 'reply'),
 ('user', 'mentions', 'user'),
 ('user', 'has_hashtag', 'hashtag'),
 ('user', 'retweeted', 'tweet'),
 ('user', 'follows', 'user')]

In [4]:
claim_df = dataset.nodes['claim']
claim_df.head()

,embedding,label,reviewers,date,language,keywords,cluster_keywords,cluster,train_mask,val_mask,test_mask
0,"[-0.04202667623758316, -0.00033039430854842067...",misinformation,[observador.pt],2020-03-15 12:30:21,pt,corona virus reaching lungs remains,coronavirus china covid 19 treatments recommended,0,True,False,False
1,"[-0.19561722874641418, -0.23915071785449982, 0...",misinformation,[observador.pt],2020-08-17 17:14:55,pt,big dubai airport,,-1,True,False,False
2,"[0.05876247584819794, 0.02175525575876236, 0.0...",misinformation,[observador.pt],2020-03-23 01:55:11,pt,news corona virus vaccine ready,coronavirus china covid 19 treatments recommended,0,True,False,False
3,"[0.05904906615614891, 0.3682330846786499, 0.00...",misinformation,[observador.pt],2018-02-19 21:05:35,pt,gardenzio stallone died morning prostate,,-1,True,False,False
4,"[0.049279212951660156, 0.021194076165556908, -...",misinformation,[observador.pt],2020-06-03 10:24:50,pt,81 blacks killed blacks 97,agency jacques attali future question finding ...,16,True,False,False

In [12]:
claim_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2165 entries, 0 to 2164
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   embedding         2165 non-null   object
 1   label             2165 non-null   category
 2   reviewers         2165 non-null   object
 3   date              2165 non-null   datetime64[ns]
 4   language          2165 non-null   category
 5   keywords          2165 non-null   object
 6   cluster_keywords  2165 non-null   category
 7   cluster           2165 non-null   category
 8   train_mask        2165 non-null   bool
 9   val_mask          2165 non-null   bool
 10  test_mask         2165 non-null   bool
dtypes: bool(3), category(4), datetime64[ns](1), object(3)
memory usage: 83.3+ KB

In [11]:
claim_df.loc[claim_df.language == 'id', :]

,embedding,label,reviewers,date,language,keywords,cluster_keywords,cluster,train_mask,val_mask,test_mask
145,"[-0.025578876957297325, 0.09601052105426788, -...",misinformation,[periksafakta.afp.com],2020-07-18,id,google apple remove palestine maps,,-1,True,False,False
148,"[-0.012159052304923534, 0.10657747834920883, -...",misinformation,[cekfakta.tempo.co],2020-07-18,id,palestine removed google maps,,-1,True,False,False
254,"[-0.09456656873226166, 0.061107587069272995, 0...",misinformation,[cekfakta.com],2021-03-08,id,people died covid 19 vaccine,coronavirus china covid 19 treatments recommended,0,True,False,False
301,"[-0.0038227590266615152, 0.15168921649456024, ...",misinformation,[cekfakta.com],2020-03-17,id,ronaldo turns hotel corona hospital,,-1,True,False,False
400,"[-0.06622577458620071, 0.06714311987161636, -0...",misinformation,[cekfakta.com],2021-02-15,id,rihanna holding national flag pakistan,,-1,True,False,False
502,"[0.08671911060810089, 0.06787948310375214, 0.0...",misinformation,[cekfakta.com],2020-10-29,id,pogba leaves french national team,french national team protest emmanuel macrons ...,7,False,True,False
503,"[0.06623732298612595, 0.27420952916145325, 0.1...",misinformation,[cekfakta.tempo.co],2020-10-26,id,pogba retires french national team,french national team protest emmanuel macrons ...,7,False,True,False
508,"[0.0713963434100151, 0.0986599326133728, 0.095...",misinformation,[periksafakta.afp.com],2020-10-26,id,pogba left french national team,french national team protest emmanuel macrons ...,7,False,True,False
529,"[-0.06984937191009521, 0.018898719921708107, -...",misinformation,[cekfakta.com],2020-05-01,id,saudi arabia celebrates end lockdown,,-1,True,False,False
601,"[-0.19976522028446198, 0.0032981985714286566, ...",misinformation,[periksafakta.afp.com],2016-02-18,id,beckham wears free west papua,,-1,True,False,False
675,"[0.013206517323851585, 0.04971480369567871, 0....",misinformation,[cekfakta.tempo.co],2021-05-10,id,video purported china spacecraft rubbing,using syrian air defense,5,True,False,False
1098,"[-0.11197861284017563, 0.036639124155044556, 0...",misinformation,[cekfakta.com],2021-01-27,id,hank aaron dies injecting covid,coronavirus china covid 19 treatments recommended,0,True,False,False
1099,"[0.03396889567375183, 0.14552393555641174, -0....",misinformation,[cekfakta.com],2020-10-27,id,putra jokowi persecutes beautiful woman,,-1,True,False,False
1100,"[-0.06530492007732391, 0.05545475706458092, -0...",misinformation,[cekfakta.com],2020-07-20,id,laser thermometer gun damage brain,coronavirus china covid 19 treatments recommended,0,True,False,False
1101,"[0.08154112845659256, -0.27618247270584106, -0...",misinformation,[cekfakta.com],2020-11-09,id,pornhub logo video appears cnn,,-1,True,False,False
1102,"[-0.03502613678574562, -0.015222067944705486, ...",misinformation,[cekfakta.com],2021-03-06,id,provision covid 19 vaccine,coronavirus china covid 19 treatments recommended,0,True,False,False
1103,"[-0.16264107823371887, 0.05785238742828369, -0...",misinformation,[cekfakta.com],2020-08-05,id,beirut storage 750 tons ammonium,using syrian air defense,5,True,False,False
1104,"[-0.07094764709472656, -0.20966167747974396, -...",misinformation,[cekfakta.com],2021-04-15,id,invents covid 19 detection microchip,coronavirus china covid 19 treatments recommended,0,True,False,False
1105,"[0.030415114015340805, 0.02783025987446308, 0....",misinformation,[cekfakta.com],2021-05-28,id,china zhurong spacecraft landing mars,taken martian sunset nasa warned asteroid,3,False,True,False
1106,"[-0.05347628518939018, -0.23163598775863647, 0...",misinformation,[cekfakta.com],2021-05-29,id,mujahideen ready jihad war tzu,chinese soldiers killed galwan valley image in...,4,False,True,False
1107,"[-0.0464949868619442, -0.05526382848620415, 0....",misinformation,[cekfakta.com],2021-05-30,id,video 2021 lunar eclipse arctic,taken martian sunset nasa warned asteroid,3,False,True,False
1109,"[0.006834540516138077, -0.08775071799755096, 0...",misinformation,[cekfakta.com],2021-06-22,id,thousands viagra inoculated mosquitoes leaving,coronavirus china covid 19 treatments recommended,0,True,False,False
1232,"[0.18767964839935303, -0.05983496829867363, -0...",misinformation,[periksafakta.afp.com],2020-08-16,id,bahrain visited dubai guard robot,,-1,True,False,False
1233,"[0.026225652545690536, -0.047187212854623795, ...",misinformation,[periksafakta.afp.com],2020-01-05,id,flag symbol revenge raised mosque,,-1,True,False,False
1812,"[-0.12221716344356537, -0.3015228807926178, 0....",misinformation,[cekfakta.tempo.co],2021-05-28,id,meteor fell summit mount merapi,taken martian sunset nasa warned asteroid,3,False,True,False
1813,"[0.009152992628514767, -0.018252020701766014, ...",misinformation,[cekfakta.tempo.co],2021-05-30,id,saturn taken inside rings cassini,taken martian sunset nasa warned asteroid,3,False,True,False
1814,"[0.06383011490106583, 0.3246859014034271, 0.01...",misinformation,[cekfakta.tempo.co],2021-06-06,id,white rhino officially declared extinct,animals affected current fires australia video...,8,True,False,False
1815,"[-0.04038918763399124, 0.015224553644657135, 0...",misinformation,[cekfakta.tempo.co],2020-10-27,id,emmanuel macron pleads middle eastern,french national team protest emmanuel macrons ...,7,False,True,False
1816,"[-0.14834372699260712, -0.13093173503875732, 0...",misinformation,[cekfakta.tempo.co],2020-08-05,id,blast beirut lebanon caused nuclear,using syrian air defense,5,True,False,False
1817,"[-0.07073820382356644, -0.06567156314849854, 0...",misinformation,[cekfakta.tempo.co],2020-01-07,id,video drone strike killed iranian,using syrian air defense,5,True,False,False
1818,"[0.024140452966094017, -0.05024508759379387, 0...",misinformation,[cekfakta.tempo.co],2021-02-14,id,virus did come bats pig,coronavirus china covid 19 treatments recommended,0,True,False,False
1819,"[-0.03664306178689003, -0.09063655138015747, -...",misinformation,[cekfakta.tempo.co],2021-04-17,id,cremation bodies amid covid tsunami,animals affected current fires australia video...,8,True,False,False

In [5]:
discusses_df = dataset.rels[('tweet', 'discusses', 'claim')]
discusses_df.head()

   src  tgt
0    0    0
1    1    1
2    2    1
3    3    1
4    4    1

In [6]:
tweet_claim_df = (tweet_df.merge(discusses_df, left_index=True, right_on='src')
                          .merge(claim_df, left_on='tgt', right_index=True)
                          .reset_index(drop=True))
tweet_claim_df.head(3)

,tweet_id,text,created_at,lang,source,num_retweets,num_replies,num_quote_tweets,src,tgt,...,label,reviewers,date,language,keywords,cluster_keywords,cluster,train_mask,val_mask,test_mask
0,1238947475471454220,Antes de llegar a los pulmones dura 4 dÃ­as en ...,2020-03-14 21:57:51,es,Twitter for Android,8,3,0,0,0,...,misinformation,[observador.pt],2020-03-15 12:30:21,pt,corona virus reaching lungs remains,coronavirus china covid 19 treatments recommended,0,True,False,False
1,1295062953000042496,Aeroporto de Dubai em chamas. ðŸ¤•ðŸ˜§ https://t.co/...,2020-08-16 18:20:43,pt,Twitter for Android,6,0,5,1,1,...,misinformation,[observador.pt],2020-08-17 17:14:55,pt,big dubai airport,,-1,True,False,False
2,1294614020008312832,Fogo ðŸ”¥ no aeroporto de Dubai ðŸ˜±ðŸ˜± https://t.co/2...,2020-08-15 12:36:49,pt,Twitter for Android,24,11,7,2,1,...,misinformation,[observador.pt],2020-08-17 17:14:55,pt,big dubai airport,,-1,True,False,False

In [8]:
tweet_claim_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4736 entries, 0 to 4735
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tweet_id          4736 non-null   uint64
 1   text              4736 non-null   object
 2   created_at        4736 non-null   datetime64[ns]
 3   lang              4736 non-null   category
 4   source            4736 non-null   object
 5   num_retweets      4736 non-null   uint64
 6   num_replies       4736 non-null   uint64
 7   num_quote_tweets  4736 non-null   uint64
 8   src               4736 non-null   int64
 9   tgt               4736 non-null   int64
 10  embedding         4736 non-null   object
 11  label             4736 non-null   category
 12  reviewers         4736 non-null   object
 13  date              4736 non-null   datetime64[ns]
 14  language          4736 non-null   category
 15  keywords          4736 non-null   object
 16  cluster_keywords  4736 non-null   category
 17  cluster           4736 non-null   category
 18  train_mask        4736 non-null   bool
 19  val_mask          4736 non-null   bool
 20  test_mask         4736 non-null   bool
dtypes: bool(3), category(5), datetime64[ns](2), int64(2), object(5), uint64(4)
memory usage: 520.2+ KB

In [11]:
list(tweet_claim_df.language.unique())

['pt',
 'en',
 'zh',
 'it',
 'hr',
 'es',
 'nl',
 'de',
 'bn',
 'id',
 'fr',
 'ar',
 'tr',
 'mk',
 'el',
 'hi',
 'sk',
 'ta',
 'ms',
 'te',
 'pa',
 'ml',
 'pl',
 'ru',
 'cs',
 'sr',
 'gu',
 'da',
 'ko',
 'th',
 'no',
 'mr',
 'ur',
 'or',
 'fa']